name: Web App Tests

# Trigger the workflow on:
on:
  push:
    branches: [ main ]           # Every push to main branch
  pull_request:                  # Every pull request
  schedule:
    - cron: '0 0 * * 1'         # Weekly on Monday at 00:00 UTC

# Security: Limit permissions to read-only
permissions:
  contents: read

jobs:
  browser-tests:
    name: Browser Tests
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Get the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'

      # Step 3: Install project dependencies
      - name: Install Node.js dependencies
        working-directory: ./app
        run: npm ci

      # Step 4: Cache Playwright browsers to speed up CI
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      # Step 5: Install Playwright browser binaries
      - name: Install Playwright browsers
        working-directory: ./app
        run: npx playwright install chromium

      # Step 6: Build the application for production-like testing
      - name: Build application
        working-directory: ./app
        run: npm run build

      # Step 7: Start the preview server in background
      - name: Start preview server
        working-directory: ./app
        run: |
          npm run preview -- --port 5173 --strictPort --host &
          echo "SERVER_PID=$!" >> $GITHUB_ENV
      
      # Step 8: Wait for server to be ready
      - name: Wait for server
        working-directory: ./app
        run: npx wait-on http://localhost:5173/ --timeout 10000

      # Step 9: Run browser tests
      - name: Run browser tests with local data
        working-directory: ./app
        run: npx playwright test --reporter=line --timeout=30000

      # Step 10: Upload test artifacts (reports, screenshots) if tests fail
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if tests fail
        with:
          name: playwright-report
          path: |
            app/playwright-report/
            app/*.png
          retention-days: 30

      # Step 11: Stop the preview server
      - name: Stop preview server
        if: always()
        run: kill $SERVER_PID || true
