name: Web App Tests

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    # Run once a week on Monday at 00:00 UTC
    - cron: '0 0 * * 1'

# Set explicit permissions
permissions:
  contents: read

jobs:
  browser-tests:
    name: Browser Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'

      - name: Install Node.js dependencies
        working-directory: ./app
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ./app
        run: npx playwright install --with-deps chromium

      - run: npm run build
        working-directory: ./app

      - run: npm install -g serve # or use vite preview
        working-directory: ./app

      - name: Start preview server
        run: npm run preview -- --port 5173 --strictPort &
        working-directory: ./app
      
      - name: Wait for server
        run: npx wait-on http://localhost:5173/ZoomingOnline/
        working-directory: ./app

      # - name: Run Playwright tests
      #   run: npx playwright test --reporter=line
      #   working-directory: ./app


      # - name: Build app
      #   run: npm run build
      #   working-directory: ./app

      - name: Run browser tests with local data
        working-directory: ./app
        run: USE_LOCAL_DATA=true npx playwright test --reporter=line

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            app/playwright-report/
            app/*.png
          retention-days: 30
