name: PR Checks

on:
  pull_request:

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev
        working-directory: python

      - name: Run check.sh
        run: bash check.sh
        working-directory: python
