name: Python Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'python/**'
  pull_request:
    paths:
      - 'python/**'

permissions:
  contents: read

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'python/.python-version'

      - name: Set up uv
        uses: ywiyogo/setup-uv@v1
        with:
          uv-version: '0.1.15'

      - name: Install dependencies
        run: uv sync --ci

      - name: Run tests
        run: uv run pytest
